 [package]
name = "airdrop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.7"
ic-cdk-macros = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
